
REM @ECHO OFF
SETLOCAL ENABLEEXTENSIONS ENABLEDELAYEDEXPANSION

IF /i "%CONFIGURATION:~0,7%"=="release" (
	IF NOT EXIST "%INSTALL_PATH%" ( MD "%INSTALL_PATH%" )
	CD "%INSTALL_PATH%"
	DEL /Q "%INSTALL_FOLDER%.zip"
	RD /Q /S "%INSTALL_FOLDER%"
	MD "%INSTALL_FOLDER%"
	@COPY "%SYMROOT%%PLATFORM_NAME%\%CONFIGURATION%\%BASE_NAME%.%WRAPPER_EXTENSION%" "%INSTALL_PATH%\%INSTALL_FOLDER%\%DISPLAY_NAME%.%WRAPPER_EXTENSION%"
	if "%RESOURCE_EXTENSION%" NEQ "" (
		@COPY "%SYMROOT%%PLATFORM_NAME%\%CONFIGURATION%\%BASE_NAME%.%RESOURCE_EXTENSION%" "%INSTALL_PATH%\%INSTALL_FOLDER%\%DISPLAY_NAME%.%RESOURCE_EXTENSION%"
	)
	CD "%INSTALL_PATH%"
	"C:\Program Files\7-Zip\7za" a -tzip "%INSTALL_FOLDER%.zip" "%INSTALL_FOLDER%\"
	IF "%LOCALISATION_SUFFIX%" == "EN-GB" (
		DEL /Q "%EXEC_PATH%\%PLUGIN_FOLDER%\%DISPLAY_NAME%.%WRAPPER_EXTENSION%"
		@COPY "%INSTALL_PATH%\%INSTALL_FOLDER%\%DISPLAY_NAME%.%WRAPPER_EXTENSION%" "%EXEC_PATH%\%PLUGIN_FOLDER%"
		if "%RESOURCE_EXTENSION%" NEQ "" (
			DEL /Q "%EXEC_PATH%\%PLUGIN_FOLDER%\%DISPLAY_NAME%.%RESOURCE_EXTENSION%"
			@COPY "%INSTALL_PATH%\%INSTALL_FOLDER%\%DISPLAY_NAME%.%RESOURCE_EXTENSION%" "%EXEC_PATH%\%PLUGIN_FOLDER%"
		)
	)
)
IF /i "%CONFIGURATION:~0,5%"=="debug" (
	IF "%LOCALISATION_SUFFIX%" == "EN-GB" (
		DEL /Q "%EXEC_PATH%\%PLUGIN_FOLDER%\%DISPLAY_NAME%.%WRAPPER_EXTENSION%"
		@COPY "%SYMROOT%%PLATFORM_NAME%\%CONFIGURATION%\%BASE_NAME%.%WRAPPER_EXTENSION%" "%EXEC_PATH%\%PLUGIN_FOLDER%\%DISPLAY_NAME%.%WRAPPER_EXTENSION%"
		if "%RESOURCE_EXTENSION%" NEQ "" (
			DEL /Q "%EXEC_PATH%\%PLUGIN_FOLDER%\%DISPLAY_NAME%.%RESOURCE_EXTENSION%"
			@COPY "%SYMROOT%%PLATFORM_NAME%\%CONFIGURATION%\%BASE_NAME%.%RESOURCE_EXTENSION%" "%EXEC_PATH%\%PLUGIN_FOLDER%\%DISPLAY_NAME%.%RESOURCE_EXTENSION%"
		)
	)
)

ENDLOCAL