# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
         repository: r-wessel/ActiveLib
         path: ActiveLib

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
      
    # - name: Build
    #   run: msbuild /m /p:Configuration=ReleaseAC27 SpeckleLib/SpeckleLib17.sln
      
    - name: Build
      run: msbuild /m /p:Configuration=ReleaseAC27 SpeckleConnector/Connector.sln
      
