# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
         repository: r-wessel/ActiveLib
         path: ActiveLib

    - name: Download zip file
      run: |
        New-Item -ItemType Directory -Path "Archicad 27" -Force
        Invoke-WebRequest -Uri "https://github.com/GRAPHISOFT/archicad-api-devkit/releases/download/27.3001/API.Development.Kit.WIN.27.3001.zip" -OutFile "file.zip"

    - name: Extract zip file to Archicad 27 folder
      run: |
        Add-Type -AssemblyName System.IO.Compression.FileSystem
        [System.IO.Compression.ZipFile]::ExtractToDirectory("file.zip", "Archicad 27")

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
      
    - name: Build
      working-directory: ./speckle-cpp-connectors
      run: msbuild /m /p:Configuration=ReleaseAC27 SpeckleConnector/Connector.sln
      
